import discontinuous_functional_differential_equations_foundation_canonical_lane_mathlib.GateLemmas
import discontinuous_functional_differential_equations_foundation_canonical_lane_mathlib.FinalTheorem
